apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m2z782j63-python 
  janus-idp.io/tekton: m2z782j63-python
  backstage.io/kubernetes-id: m2z782j63-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m2z782j63-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml