apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: m2z782j63-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m2z782j63-python 
  name: m2z782j63-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: m2z782j63-python 
